import { Farm, Order, Product } from '../types';

export const rowToOrder = (row: any): Order => ({
  id: row.id,
  traceCode: row.trace_code,
  placedAt: row.placed_at,
  items: row.items,
  subtotal: Number(row.subtotal),
  deliveryFee: Number(row.delivery_fee),
  total: Number(row.total),
  deliveryAddress: row.delivery_address,
  paymentMethod: row.payment_method,
  status: row.status,
  estimatedDelivery: row.estimated_delivery,
  farmIds: row.farm_ids || [],
  traceEvents: row.trace_events || [],
  paymentStatus: row.payment_status,
  paymentReference: row.payment_reference,
  paidAt: row.paid_at,
  createdAt: row.created_at,
  customerName: row.customer_name,
  customerPhone: row.customer_phone,
  customerEmail: row.customer_email,
  userId: row.user_id,
});

export const rowToProduct = (r: any): Product => ({
  id: r.id,
  name: r.name,
  localName: r.local_name ?? undefined,
  category: r.category,
  price: Number(r.price),
  originalPrice: Number(r.original_price ?? r.price),
  discountPercent: Number(r.discount_percent ?? 0),
  unit: r.unit ?? '',
  weight: r.weight ?? '',
  images: r.images ?? [],
  farmId: r.farm_id ?? '',
  description: r.description ?? '',
  healthTags: r.health_tags ?? [],
  inStock: r.in_stock ?? true,
  stockCount: r.stock_count ?? 0,
  harvestDate: r.harvest_date ?? '',
  shelfLife: r.shelf_life ?? '',
  nutritionHighlights: r.nutrition_highlights ?? [],
});

export const rowToFarm = (r: any): Farm => ({
  id: r.id,
  name: r.name,
  cluster: r.cluster ?? '',
  location: r.location ?? '',
  region: r.region ?? '',
  bio: r.bio ?? '',
  practices: r.practices ?? [],
  certifications: r.certifications ?? [],
  photo: r.photo ?? '',
  farmerName: r.farmer_name ?? '',
  farmerPhoto: r.farmer_photo ?? '',
  rating: Number(r.rating ?? 0),
  reviewsCount: r.reviews_count ?? 0,
  establishedYear: r.established_year ?? 0,
  phone: r.phone ?? '',
  coordinates: { lat: Number(r.lat ?? 0), lng: Number(r.lng ?? 0) },
});
